### ISSUE TITLE
F:\laragon\www\FastLaravel\vendor\symfony\var-dumper\Dumper\HtmlDumper.php:120

### ISSUE THREAD

**Issue by MoSogbe** [FastXGroup/FastLaravel#2]
F:\laragon\www\FastLaravel\vendor\symfony\var-dumper\Dumper\HtmlDumper.php:120

**Comment by devhau** [comment]
You can use : `composer update`
update lasted package:ymfony\var-dumper
Fixed: https://github.com/symfony/var-dumper/commit/3dd8ddd1e260e58ecc61bb78da3b6584b3bfcba0

**Comment by devhau** [comment]
Fix see: https://www.youtube.com/watch?v=luicxwZoFlE
